ignoreFiles:
  - node_modules
  - build/**/*
plugins:
  - stylelint-scss
# See https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md
rules:
  block-closing-brace-newline-after:
    - always
    - ignoreAtRules:
      # Ignore @if … @else in SCSS.
      - if
      - else
  block-no-empty: true
  block-opening-brace-space-before: always
  color-hex-case: lower
  color-hex-length: short
  color-named: never
  color-no-invalid-hex: true
  comment-no-empty: true
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-block-no-duplicate-properties: true
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-single-line-max-declarations: 1
  declaration-block-trailing-semicolon: always
  declaration-colon-space-after: always
  declaration-colon-space-before: never
  declaration-property-value-blacklist:
    - /^border/: [none]
    - severity: error
  declaration-no-important: true
  font-family-no-duplicate-names: true
  function-calc-no-unspaced-operator: true
  function-comma-newline-after: always-multi-line
  function-comma-newline-before: never-multi-line
  function-comma-space-after: always-single-line
  function-comma-space-before: never
  function-linear-gradient-no-nonstandard-direction: true
  function-max-empty-lines: 0
  function-name-case: lower
  function-parentheses-newline-inside: always-multi-line
  function-parentheses-space-inside: never-single-line
  function-url-quotes: always
  function-whitespace-after: always
  indentation:
    - 4
    - severity: error
  length-zero-no-unit: true
  max-nesting-depth: 3
  media-feature-name-no-unknown: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-missing-end-of-source-newline: true
  number-no-trailing-zeros: true
  number-leading-zero: always
  property-case: lower
  property-no-unknown: true
  property-no-vendor-prefix: true
  rule-empty-line-before:
    - always
    - except:
      - after-single-line-comment
      - first-nested
  selector-no-qualifying-type:
    - true
    - ignore:
      - attribute
      - class
  selector-list-comma-space-before: never
  selector-list-comma-newline-after: always
  selector-max-id: 0
  selector-pseudo-element-colon-notation: double
  selector-pseudo-element-no-unknown: true
  selector-type-no-unknown: true
  string-no-newline: true
  string-quotes: single
  unit-no-unknown: true
  unit-case: lower
  value-no-vendor-prefix: true
  # SCSS Lint settings
  scss/at-import-no-partial-leading-underscore: true
  scss/at-import-partial-extension-blacklist:
    - scss
  scss/at-else-empty-line-before: never
  scss/at-rule-no-unknown: true
  scss/media-feature-value-dollar-variable: always
  scss/selector-no-redundant-nesting-selector: true
